// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paroevrvqvfdsvlgohgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcm9ldnJ2cXZmZHN2bGdvaGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzI5ODcsImV4cCI6MjA2ODI0ODk4N30.p4c-iNiIULjn2WNFrgf95UpDIEVrK5vfO6BNWb4eenQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});